title: Yalestar
description: Forever your girl
remote_theme: pages-themes/dinky@v0.2.0
show_downloads: false
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

plugins:
- jekyll-remote-theme

exclude:
  - Gemfile
  - Gemfile.lock
